language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t vasanthsumanath/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vasanthsumanath/react-test npm test

after_success:
  - docker build -t vasanthsumanath/multi-client ./client
  - docker build -t vasanthsumanath/multi-server ./server
  - docker build -t vasanthsumanath/multi-worker ./worker
  - docker build -t vasanthsumanath/multi-nginx ./nginx
  #Login to Docker hub
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
  #push the images to docker hub
  - docker push vasanthsumanath/multi-client
  - docker push vasanthsumanath/multi-server
  - docker push vasanthsumanath/multi-worker
  - docker push vasanthsumanath/multi-nginx
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-111601026487
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

